### ISSUE TITLE
cell_type_names not found

### ISSUE THREAD

**Issue by JenniferWUSTL** [dmcable/RCTD#26]
Good afternoon!

We are excited to test RCTD on our 10x Visium data; however, I am running into some errors that I can't figure out with the create.RCTD:
```
library(Seurat)
library(RCTD)
library(Matrix)
nuclei <- readRDS("snRNAseq_filtered_3-8-21.rds") # reading in a Seurat object
# remove cell types with less than 25 cells
nuclei <- subset(nuclei, idents = c("Unk_1", "Unk_2"), invert = TRUE)
print("exporting data to create RCTD ref")
counts <- as.matrix(GetAssayData(nuclei, slot = "counts", assay = "RNA"))
meta <- as.matrix(nuclei@meta.data) 
cell_types <- meta[,"Cell_Types_Main",drop = TRUE] 
cell_types <- as.factor(cell_types) # wants cell types as factor
names(cell_types) <- rownames(meta)
nUMI <- meta[,"nCount_RNA",drop = TRUE]
nUMI <- as.numeric(nUMI)
names(nUMI) <- rownames(meta)
reference <- Reference(counts, cell_types, nUMI)
# see below for R 4.0 warning since matrixes are now also arrays
#Warning messages:
  #1: In if (class(counts) != "dgCMatrix") { :
      #the condition has length > 1 and only the first element will be used
   # 2: In if (class(counts) != "matrix") tryCatch({ :
       # the condition has length > 1 and only the first element will be used
# reference is class RCTD with 3 slots- @cell_types, @counts,@nUMI
spatial <- readRDS("spatial_initialpilot_3-8-21.rds")
coords <- GetTissueCoordinates(spatial, scale = NULL) # pulling unscaled tissue coordinates
spatialcounts <- as.matrix(GetAssayData(spatial, assay = "Spatial", slot = "counts"))
spatialmeta <- spatial@meta.data
spatialnUMI <- spatialmeta[,"nCount_Spatial", drop = TRUE]
names(spatialnUMI) <- rownames(spatialmeta)
puck <- SpatialRNA(coords, spatialcounts, spatialnUMI)
#Warning messages:
  #1: In if (class(counts) != "dgCMatrix") { :
     # the condition has length > 1 and only the first element will be used
    #2: In if (class(counts) != "matrix") tryCatch({ :
       # the condition has length > 1 and only the first element will be used
barcodes <- colnames(puck@counts)
myRCTD <- create.RCTD(puck, reference)
[1] "Begin: process_cell_type_info"
[1] "process_cell_type_info: number of cells in reference: 5793"
[1] "process_cell_type_info: number of genes in reference: 18589"

  astrocyte_GFAPneg   astrocyte_GFAPpos           microglia             neurons 
                289                 249                2751                 179 
    oligodendrocyte oligodendrocyte_pre 
               2040                 285 
Error in get_cell_type_info(reference@counts, reference@cell_types, reference@nUMI,  : 
                              argument "cell_type_names" is missing, with no default
```

I've tried passing a character string to create.RCTD for cell_type_names, and I also tried using the Seurat object as the reference instead of creating the RCTD object but in that case, it cannot find the counts slot of the Seurat object:

```
myRCTD <- create.RCTD(spatial, nuclei, cell_type_names = "Cell_Types_Main")
[1] "Begin: process_cell_type_info"
Error in paste("process_cell_type_info: number of cells in reference:",  : 
  no slot of name "counts" for this object of class "Seurat"
```

What do you advise to overcome this error?

Thank you!!

Here is the output of my R session:```
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RCTD_1.1.0         SeuratObject_4.0.0 Seurat_4.0.1      

loaded via a namespace (and not attached):
  [1] nlme_3.1-147          matrixStats_0.58.0    spatstat.sparse_2.0-0
  [4] doParallel_1.0.16     RcppAnnoy_0.0.18      RColorBrewer_1.1-2   
  [7] httr_1.4.1            sctransform_0.3.2     tools_4.0.0          
 [10] utf8_1.2.1            R6_2.5.0              irlba_2.3.3          
 [13] rpart_4.1-15          KernSmooth_2.23-16    uwot_0.1.10          
 [16] mgcv_1.8-31           DBI_1.1.0             lazyeval_0.2.2       
 [19] colorspace_2.0-0      tidyselect_1.1.0      gridExtra_2.3        
 [22] compiler_4.0.0        plotly_4.9.3          scales_1.1.1         
 [25] lmtest_0.9-38         spatstat.data_2.1-0   ggridges_0.5.3       
 [28] pbapply_1.4-3         goftest_1.2-2         stringr_1.4.0        
 [31] digest_0.6.27         spatstat.utils_2.1-0  pkgconfig_2.0.3      
 [34] htmltools_0.4.0       fastmap_1.0.1         htmlwidgets_1.5.3    
 [37] rlang_0.4.10          shiny_1.4.0.2         generics_0.1.0       
 [40] zoo_1.8-8             jsonlite_1.6.1        ica_1.0-2            
 [43] dplyr_1.0.5           magrittr_2.0.1        patchwork_1.1.1      
 [46] Matrix_1.3-2          Rcpp_1.0.6            munsell_0.5.0        
 [49] fansi_0.4.2           abind_1.4-5           reticulate_1.16      
 [52] lifecycle_1.0.0       stringi_1.5.3         MASS_7.3-51.5        
 [55] Rtsne_0.15            plyr_1.8.6            grid_4.0.0           
 [58] blob_1.2.1            parallel_4.0.0        listenv_0.8.0        
 [61] promises_1.1.0        ggrepel_0.9.1         crayon_1.4.1         
 [64] miniUI_0.1.1.1        deldir_0.1-25         lattice_0.20-41      
 [67] cowplot_1.1.1         splines_4.0.0         tensor_1.5           
 [70] pillar_1.5.1          igraph_1.2.6          spatstat.geom_2.0-1  
 [73] future.apply_1.7.0    reshape2_1.4.4        codetools_0.2-16     
 [76] leiden_0.3.7          glue_1.4.2            data.table_1.14.0    
 [79] foreach_1.5.1         vctrs_0.3.6           png_0.1-7            
 [82] httpuv_1.5.4          gtable_0.3.0          RANN_2.6.1           
 [85] purrr_0.3.4           spatstat.core_2.0-0   polyclip_1.10-0      
 [88] tidyr_1.1.3           scattermore_0.7       future_1.17.0        
 [91] assertthat_0.2.1      ggplot2_3.3.3         mime_0.9             
 [94] xtable_1.8-4          later_1.1.0.1         survival_3.1-12      
 [97] viridisLite_0.3.0     tibble_3.1.0          iterators_1.0.13     
[100] cluster_2.1.0         globals_0.12.5        fitdistrplus_1.1-3   
[103] ellipsis_0.3.1        ROCR_1.0-11          
```

**Comment by JenniferWUSTL** [comment]
I was able to get create.RCTD to run by changing the source code (my addition in bold):create.RCTD <- function(spatialRNA, reference, max_cores = 8, test_mode = FALSE, gene_cutoff = 0.000125, fc_cutoff = 0.5, gene_cutoff_reg = 0.0002, fc_cutoff_reg = 0.75, UMI_min = 100, UMI_max = 200000,
                        class_df = NULL, CELL_MIN_INSTANCE = 25, cell_type_names = NULL) {
  
  config <- list(gene_cutoff = gene_cutoff, fc_cutoff = fc_cutoff, gene_cutoff_reg = gene_cutoff_reg, fc_cutoff_reg = fc_cutoff_reg, UMI_min = UMI_min, max_cores = max_cores,
                 N_epoch = 8, N_X = 50000, K_val = 100, N_fit = 1000, N_epoch_bulk = 30, MIN_CHANGE_BULK = 0.0001, MIN_CHANGE_REG = 0.001, UMI_max = UMI_max, MIN_OBS = 3)
  if(test_mode)
    config <- list(gene_cutoff = .00125, fc_cutoff = 0.5, gene_curoff_reg = 0.002, fc_cutoff_reg = 0.75, UMI_min = 1000,
                   N_epoch = 1, N_X = 50000, K_val = 100, N_fit = 50, N_epoch_bulk = 4, MIN_CHANGE_BULK = 1, MIN_CHANGE_REG = 0.001, UMI_max = 200000, MIN_OBS = 3, max_cores = 1)
  if(is.null(cell_type_names))
    cell_type_names <- levels(reference@cell_types)
  cell_type_info <- list(info = process_cell_type_info(reference, **cell_type_names**,CELL_MIN = CELL_MIN_INSTANCE), renorm = NULL)
  
  puck = restrict_counts(spatialRNA, rownames(spatialRNA@counts), UMI_thresh = config$UMI_min, UMI_max = config$UMI_max)
  print('create.RCTD: getting regression differentially expressed genes: ')
  #puckMeans <- rowMeans(sweep(puck@counts, 2 , puck@nUMI, '/'))
  gene_list_reg = get_de_genes(cell_type_info$info, puck, fc_thresh = config$fc_cutoff_reg, expr_thresh = config$gene_cutoff_reg, MIN_OBS = config$MIN_OBS)
  if(length(gene_list_reg) == 0)
    stop("create.RCTD: Error: 0 regression differentially expressed genes found")
  print('create.RCTD: getting platform effect normalization differentially expressed genes: ')
  gene_list_bulk = get_de_genes(cell_type_info$info, puck, fc_thresh = config$fc_cutoff, expr_thresh = config$gene_cutoff, MIN_OBS = config$MIN_OBS)
  if(length(gene_list_bulk) == 0)
    stop("create.RCTD: Error: 0 bulk differentially expressed genes found")
  puck = restrict_counts(puck, gene_list_bulk, UMI_thresh = config$UMI_min, UMI_max = config$UMI_max)
  puck = restrict_puck(puck, colnames(puck@counts))
  if(is.null(class_df))
    class_df <- data.frame(cell_type_info$info[[2]], row.names = cell_type_info$info[[2]]); colnames(class_df)[1] = "class"
  internal_vars <- list(gene_list_reg = gene_list_reg, gene_list_bulk = gene_list_bulk, proportions = NULL, class_df = class_df)
  new("RCTD", spatialRNA = puck, reference = reference, config = config, cell_type_info = cell_type_info, internal_vars = internal_vars)
}       
                   
I believe this accurately fixes the error, but let me know your thoughts.

I'm also finding `gather_results` and `get_decomposed_data` functions to not be present in my RCTD version, which might contribute to why I am having trouble with `plot_all_cell_types` as my results has no `results$results_df`.  I recently installed RCTD from github, but my version is listed as 1.1, so perhaps that could be a contributing cause?

I appreciate your time and attention and look forward to taking advantage of this package.  Let me know if you need any further details regarding my issues. Thank you!!

**Comment by dmcable** [comment]
Happy to help, and thank you for your interest in this package!

For the first issue, yes dropping `cell_type_names` was a common issue that we have fixed in a recent pull request. Thank you for noting that. Updating the package should fix this issue.

For your second question, I think the issue is that `gather_results` is an internal function of RCTD (not exported by default), so if you wanted to use that function (shouldn't have to!), you would have to copy and paste it in as well. I think if you go back to using the official version of `create.RCTD`, this should fix your trouble and enable `plot_all_cell_types`. 

We have temporarily removed `get_decomposed_data` while we are making it compatible with the current version, but this function is not necessary to the core functionality of RCTD, and it will eventually be available again.

**Comment by JenniferWUSTL** [comment]
Good morning!  Thank you for replying to my issue so quickly!  When I try to update the package version with `devtools::install_github("dmcable/RCTD", build_vignettes = FALSE)` I am still getting version 1.1, how do you suggest to update to 1.2? 

Thank you!!

**Comment by dmcable** [comment]
Hello,

I believe that the issue could be caused because the package has not changed since you last tried to install (except for the version number). You could try running `devtools::install_github("dmcable/RCTD", build_vignettes = FALSE, force = TRUE)`. Shouldn't affect the functionality of the code. Hope this helps.

Dylan
